# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Promotigo Production - Microsoft'
    subscriptionId: 'fe9c7522-c3b5-4fec-ac4c-2ba3e9eac493'
    location: 'North Europe'
    templateLocation: 'deploy/template.json'
    deploymentMode: 'Incremental'

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
