# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Promotigo Production - Microsoft'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'func-ndl-cer-all-ne2-1'    
    subscriptionId: 'fe9c7522-c3b5-4fec-ac4c-2ba3e9eac493'
    location: 'North Europe'
    templateLocation: 'deploy/template.json'
    deploymentMode: 'Incremental'
